# Generated by Django 3.0 on 2019-12-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='email',
            field=models.EmailField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='snippet',
            name='phno',
            field=models.IntegerField(default=0, max_length=80),
        ),
    ]
