# Generated by Django 2.1.5 on 2019-12-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20191212_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='phno',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
